# Generated by Django 5.1.5 on 2025-03-13 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('tipo_historia', models.CharField(choices=[('Crisis Epiléptica', 'Crisis Epiléptica'), ('Consulta', 'Consulta'), ('Tratamiento', 'Tratamiento'), ('Otro', 'Otro')], max_length=50)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historias_clinicas', to='pacientes.paciente')),
            ],
        ),
    ]
